Repository CarterLankford/MentorExercises, pull requests merged in 2019-06, with the labels that each got.

#18 Feature/implement undo 13
  TowerOfHanoi/DynamicStack.java
  TowerOfHanoi/Launcher.java
  TowerOfHanoi/Node.java
Labels: 0-Backlog, Feature, P2

#20 Adding ground rules to README file
  README.md
Labels: 0-Backlog, Feature, P2

#22 Challenge/implement challenges 16
  Challenges/MyStringSplit.java
  Challenges/StringSplitting.java
Labels: 0-Backlog, Challenge, P2

#19 Feature/design 14
  Rock’n Roll Payroll/doc/Rock'nRollPayRoleUML.mdj
Labels: 0-Backlog, Feature, P1
